import streamlit as st
import json
import nlp.intent_matcher as intent_matcher

def generate_ai_questions(topic, num_questions=5):
    """Use Gemini AI to generate aptitude questions on a given topic."""
    if not intent_matcher.is_gemini_active():
        return None
    
    prompt = (
        f"Generate exactly {num_questions} multiple-choice aptitude questions on the topic: '{topic}'.\n\n"
        f"Return ONLY valid JSON in this exact format, no extra text:\n"
        f'{{"questions": [\n'
        f'  {{"question": "question text", "options": ["A) option1", "B) option2", "C) option3", "D) option4"], "answer": "A) option1", "explanation": "brief explanation"}}\n'
        f']}}\n\n'
        f"Rules:\n"
        f"- Make questions progressively harder (easy to hard)\n"
        f"- Include numerical/calculation questions where appropriate\n"
        f"- Explanations should show step-by-step solutions\n"
        f"- Options must start with A), B), C), D)\n"
        f"- The answer must exactly match one of the options"
    )
    
    try:
        response = intent_matcher._ask_gemini(prompt)
        if not response:
            return None
        
        response = response.replace("```json", "").replace("```", "").strip()
        start = response.find("{")
        end = response.rfind("}") + 1
        if start >= 0 and end > start:
            json_str = response[start:end]
            data = json.loads(json_str)
            return data.get("questions", [])
    except Exception as e:
        st.error(f"Error parsing AI response: {str(e)}")
    
    return None

def render_page():
    st.title("🧠 Aptitude Practice")
    st.write("Generate fresh aptitude questions on any topic using AI!")
    
    if not intent_matcher.is_gemini_active():
        st.warning("Please add your Gemini API key in the `.env` file to use AI-generated questions.")
        st.markdown("""
        ### How to enable:
        1. Open the file `.env` in your project folder
        2. Replace `PASTE_YOUR_KEY_HERE` with your Gemini API key
        3. Restart the app
        """)
        return
    
    st.subheader("🤖 AI-Powered Question Generator")
    
    # Quick topic buttons
    st.markdown("**Quick Topics:**")
    quick_topics = ["Percentages", "Time & Work", "Probability", "Profit & Loss", 
                    "Blood Relations", "Coding-Decoding", "Syllogisms", "Number Series"]
    
    cols = st.columns(4)
    selected_quick = None
    for i, topic in enumerate(quick_topics):
        with cols[i % 4]:
            if st.button(topic, key=f"quick_{topic}"):
                selected_quick = topic
    
    st.markdown("---")
    
    # Custom topic input
    col1, col2 = st.columns([3, 1])
    with col1:
        topic = st.text_input(
            "Or enter a custom topic",
            value=selected_quick if selected_quick else "",
            placeholder="e.g., Permutations, Data Interpretation, Averages..."
        )
    with col2:
        num_q = st.selectbox("Questions", [3, 5, 8, 10], index=1)
    
    if st.button("🚀 Generate Questions", type="primary") or selected_quick:
        actual_topic = selected_quick if selected_quick else topic
        if not actual_topic:
            st.warning("Please enter a topic or click a quick topic button!")
        else:
            with st.spinner(f"AI is generating {num_q} questions on '{actual_topic}'..."):
                questions = generate_ai_questions(actual_topic, num_q)
            
            if questions:
                st.session_state.ai_questions = questions
                st.session_state.ai_topic = actual_topic
                st.session_state.ai_score = 0
                st.session_state.ai_answered = {}
                st.rerun()
            else:
                st.error("Could not generate questions. Try a different topic.")
    
    # Display generated questions
    if "ai_questions" in st.session_state and st.session_state.ai_questions:
        st.markdown(f"### Topic: {st.session_state.ai_topic}")
        st.markdown(f"*{len(st.session_state.ai_questions)} questions generated by Gemini AI*")
        st.markdown("---")
        
        for i, q in enumerate(st.session_state.ai_questions):
            st.markdown(f"**Q{i+1}: {q['question']}**")
            
            user_choice = st.radio(
                "Select your answer:",
                q["options"],
                key=f"ai_q_{i}",
                index=None
            )
            
            if st.button("Check Answer", key=f"ai_btn_{i}"):
                if i not in st.session_state.ai_answered:
                    if user_choice == q["answer"]:
                        st.success("Correct! 🎉")
                        st.session_state.ai_score += 1
                    else:
                        st.error(f"Incorrect. The correct answer is **{q['answer']}**")
                    st.info(f"**Explanation:** {q['explanation']}")
                    st.session_state.ai_answered[i] = True
                else:
                    if user_choice == q["answer"]:
                        st.success("Correct! 🎉")
                    else:
                        st.error(f"Incorrect. The correct answer is **{q['answer']}**")
                    st.info(f"**Explanation:** {q['explanation']}")
            
            st.markdown("---")
        
        # Score summary
        answered = len(st.session_state.ai_answered)
        total = len(st.session_state.ai_questions)
        if answered > 0:
            score = st.session_state.ai_score
            percentage = (score / answered) * 100
            
            col1, col2, col3 = st.columns(3)
            with col1:
                st.metric("Score", f"{score}/{answered}")
            with col2:
                st.metric("Percentage", f"{percentage:.0f}%")
            with col3:
                st.metric("Remaining", f"{total - answered}")
        
        if st.button("🔄 Generate New Questions", type="primary"):
            del st.session_state.ai_questions
            del st.session_state.ai_topic
            del st.session_state.ai_score
            del st.session_state.ai_answered
            st.rerun()
